package pageobject.LMSS;

import generallib.General;

import java.net.URLDecoder;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Random;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import lib.DB;
import lib.Reporter;
import lib.Stock;

import org.w3c.dom.Document;

import com.aventstack.extentreports.Status;

import core.framework.Globals;

public class LMSS_Std_Loan_Struc {

	public String queryString;
	private String serviceURL =  "http://" + Stock.getConfigParam("TargetServiceHostServer").trim() + ":8080/ServiceManager/Macro/ExecMacro/LMSS_Loan_Standard_Structure";
	private DocumentBuilderFactory docBuilderFactory;
	private DocumentBuilder docBuilder;
	private Document doc;
	public ResultSet queryResultSet = null;

	String CONTROL_SELECTION_0;
	String LOGON_DATABASE;
	String LOGON_PASSWORD;
	String LOGON_USERNAME;
	String STD_LOAN_STRUC_CODE_0;
	String STD_LOAN_STRUC_STRUC_DESCR_0;
	String STD_LOAN_STRUC_LOAN_TYPE_CODE_0;
	String STD_LOAN_STRUC_EFFDATE_0;
	String STD_LOAN_STRUC_EFFDATE_MTHD_DAYS_0;
	String STD_LOAN_STRUC_COLLATERAL_FACTOR_0;
	String STD_LOAN_STRUC_MIN_LOAN_AMT_0;
	String STD_LOAN_STRUC_DEBIT_METHOD_CODE_0;
	String STD_LOAN_STRUC_CONSOLIDATE_IND_CONSOLIDATE_NO_RAD_BUT_0;
	String STD_LOAN_STRUC_REPAY_MTHD_CODE_0;
	String STD_LOAN_STRUC_REPAY_TOLERANCE_AMT_0;
	String STD_LOAN_STRUC_REPAY_CURE_PERD_DAYS_0;
	String STD_LOAN_STRUC_DEFAULT_TYPE_CODE_0;
	String STD_LOAN_STRUC_PREPAY_ALLOWED_CODE_0;
	String STD_LOAN_STRUC_PAYOFF_TOLERANCE_AMT_0;
	String STD_LOAN_STRUC_PAY_AHEAD_MAX_DAYS_0;
	String STD_LOAN_STRUC_EARLY_PAYOFF_INT_DAYS_0;
	String STD_LOAN_STRUC_EARLY_PAYOFF_GRACE_DAYS_0;
	String STD_LOAN_STRUC_SDIRTY_CODE_0;
	String STD_LOAN_STRUC_INT_RATE_TYPE_CODE_0;
	String STD_LOAN_FEE_CODE_0;
	String STD_LOAN_FEE_EFFDATE_0;
	String STD_LOAN_FEE_AMOUNT_0;
	String STD_LOAN_FEE_MTHD_CODE_0;
	String STD_LOAN_TERM_LOAN_REASON_CODE_0;
	String STD_LOAN_TERM_LOW_THRESH_0;
	String STD_LOAN_TERM_HIGH_THRESH_0;
	String STD_LOAN_TERM_LOAN_TERM_QUAL_0;
	String STD_INT_RATE_ADJ_START_DATE_0;
	String STD_INT_RATE_ADJ_VALUE_0;
	String STD_LOAN_MAX_AMT_LOW_THRESH_0;
	String STD_LOAN_MAX_AMT_HIGH_THRESH_0;
	String STD_LOAN_MAX_AMT_PERCENT_0;
	String STD_LOAN_MAX_AMT_LOW_THRESH_1;
	String STD_LOAN_MAX_AMT_HIGH_THRESH_1;
	String STD_LOAN_MAX_AMT_AMOUNT_1;
	String STD_LOAN_STRUC_PREPAY_RESTRC_PERD_0;
	String STD_LOAN_STRUC_PREPAY_RESTRC_QUAL_0;
	String STD_LOAN_STRUC_FULL_PREPAY_ALLOWED_IND_FULL_PREPAY_NO_0;
	String STD_LOAN_STRUC_PAY_AHEAD_ALLOWED_IND_PAY_AHEAD_NO_0;
	String STD_LOAN_STRUC_PRINCIPAL_REDUCTION_ALLOW_IND_PRINCIPAL_REDUCTION_NO_0;
	public void setCONTROL_SELECTION_0(String cONTROL_SELECTION_0) {
		CONTROL_SELECTION_0 = cONTROL_SELECTION_0;
	}
	public void setLOGON_DATABASE(String lOGON_DATABASE) {
		LOGON_DATABASE = lOGON_DATABASE;
	}
	public void setLOGON_PASSWORD(String lOGON_PASSWORD) {
		LOGON_PASSWORD = lOGON_PASSWORD;
	}
	public void setLOGON_USERNAME(String lOGON_USERNAME) {
		LOGON_USERNAME = lOGON_USERNAME;
	}
	public void setSTD_LOAN_STRUC_CODE_0(String sTD_LOAN_STRUC_CODE_0) {
		STD_LOAN_STRUC_CODE_0 = sTD_LOAN_STRUC_CODE_0;
	}
	public void setSTD_LOAN_STRUC_STRUC_DESCR_0(String sTD_LOAN_STRUC_STRUC_DESCR_0) {
		STD_LOAN_STRUC_STRUC_DESCR_0 = sTD_LOAN_STRUC_STRUC_DESCR_0;
	}
	public void setSTD_LOAN_STRUC_LOAN_TYPE_CODE_0(
			String sTD_LOAN_STRUC_LOAN_TYPE_CODE_0) {
		STD_LOAN_STRUC_LOAN_TYPE_CODE_0 = sTD_LOAN_STRUC_LOAN_TYPE_CODE_0;
	}
	public void setSTD_LOAN_STRUC_EFFDATE_0(String sTD_LOAN_STRUC_EFFDATE_0) {
		STD_LOAN_STRUC_EFFDATE_0 = sTD_LOAN_STRUC_EFFDATE_0;
	}
	public void setSTD_LOAN_STRUC_EFFDATE_MTHD_DAYS_0(
			String sTD_LOAN_STRUC_EFFDATE_MTHD_DAYS_0) {
		STD_LOAN_STRUC_EFFDATE_MTHD_DAYS_0 = sTD_LOAN_STRUC_EFFDATE_MTHD_DAYS_0;
	}
	public void setSTD_LOAN_STRUC_COLLATERAL_FACTOR_0(
			String sTD_LOAN_STRUC_COLLATERAL_FACTOR_0) {
		STD_LOAN_STRUC_COLLATERAL_FACTOR_0 = sTD_LOAN_STRUC_COLLATERAL_FACTOR_0;
	}
	public void setSTD_LOAN_STRUC_MIN_LOAN_AMT_0(
			String sTD_LOAN_STRUC_MIN_LOAN_AMT_0) {
		STD_LOAN_STRUC_MIN_LOAN_AMT_0 = sTD_LOAN_STRUC_MIN_LOAN_AMT_0;
	}
	public void setSTD_LOAN_STRUC_DEBIT_METHOD_CODE_0(
			String sTD_LOAN_STRUC_DEBIT_METHOD_CODE_0) {
		STD_LOAN_STRUC_DEBIT_METHOD_CODE_0 = sTD_LOAN_STRUC_DEBIT_METHOD_CODE_0;
	}
	public void setSTD_LOAN_STRUC_CONSOLIDATE_IND_CONSOLIDATE_NO_RAD_BUT_0(
			String sTD_LOAN_STRUC_CONSOLIDATE_IND_CONSOLIDATE_NO_RAD_BUT_0) {
		STD_LOAN_STRUC_CONSOLIDATE_IND_CONSOLIDATE_NO_RAD_BUT_0 = sTD_LOAN_STRUC_CONSOLIDATE_IND_CONSOLIDATE_NO_RAD_BUT_0;
	}
	public void setSTD_LOAN_STRUC_REPAY_MTHD_CODE_0(
			String sTD_LOAN_STRUC_REPAY_MTHD_CODE_0) {
		STD_LOAN_STRUC_REPAY_MTHD_CODE_0 = sTD_LOAN_STRUC_REPAY_MTHD_CODE_0;
	}
	public void setSTD_LOAN_STRUC_REPAY_TOLERANCE_AMT_0(
			String sTD_LOAN_STRUC_REPAY_TOLERANCE_AMT_0) {
		STD_LOAN_STRUC_REPAY_TOLERANCE_AMT_0 = sTD_LOAN_STRUC_REPAY_TOLERANCE_AMT_0;
	}
	public void setSTD_LOAN_STRUC_REPAY_CURE_PERD_DAYS_0(
			String sTD_LOAN_STRUC_REPAY_CURE_PERD_DAYS_0) {
		STD_LOAN_STRUC_REPAY_CURE_PERD_DAYS_0 = sTD_LOAN_STRUC_REPAY_CURE_PERD_DAYS_0;
	}
	public void setSTD_LOAN_STRUC_DEFAULT_TYPE_CODE_0(
			String sTD_LOAN_STRUC_DEFAULT_TYPE_CODE_0) {
		STD_LOAN_STRUC_DEFAULT_TYPE_CODE_0 = sTD_LOAN_STRUC_DEFAULT_TYPE_CODE_0;
	}
	public void setSTD_LOAN_STRUC_PREPAY_ALLOWED_CODE_0(
			String sTD_LOAN_STRUC_PREPAY_ALLOWED_CODE_0) {
		STD_LOAN_STRUC_PREPAY_ALLOWED_CODE_0 = sTD_LOAN_STRUC_PREPAY_ALLOWED_CODE_0;
	}
	public void setSTD_LOAN_STRUC_PAYOFF_TOLERANCE_AMT_0(
			String sTD_LOAN_STRUC_PAYOFF_TOLERANCE_AMT_0) {
		STD_LOAN_STRUC_PAYOFF_TOLERANCE_AMT_0 = sTD_LOAN_STRUC_PAYOFF_TOLERANCE_AMT_0;
	}
	public void setSTD_LOAN_STRUC_PAY_AHEAD_MAX_DAYS_0(
			String sTD_LOAN_STRUC_PAY_AHEAD_MAX_DAYS_0) {
		STD_LOAN_STRUC_PAY_AHEAD_MAX_DAYS_0 = sTD_LOAN_STRUC_PAY_AHEAD_MAX_DAYS_0;
	}
	public void setSTD_LOAN_STRUC_EARLY_PAYOFF_INT_DAYS_0(
			String sTD_LOAN_STRUC_EARLY_PAYOFF_INT_DAYS_0) {
		STD_LOAN_STRUC_EARLY_PAYOFF_INT_DAYS_0 = sTD_LOAN_STRUC_EARLY_PAYOFF_INT_DAYS_0;
	}
	public void setSTD_LOAN_STRUC_EARLY_PAYOFF_GRACE_DAYS_0(
			String sTD_LOAN_STRUC_EARLY_PAYOFF_GRACE_DAYS_0) {
		STD_LOAN_STRUC_EARLY_PAYOFF_GRACE_DAYS_0 = sTD_LOAN_STRUC_EARLY_PAYOFF_GRACE_DAYS_0;
	}
	public void setSTD_LOAN_STRUC_SDIRTY_CODE_0(String sTD_LOAN_STRUC_SDIRTY_CODE_0) {
		STD_LOAN_STRUC_SDIRTY_CODE_0 = sTD_LOAN_STRUC_SDIRTY_CODE_0;
	}
	public void setSTD_LOAN_STRUC_INT_RATE_TYPE_CODE_0(
			String sTD_LOAN_STRUC_INT_RATE_TYPE_CODE_0) {
		STD_LOAN_STRUC_INT_RATE_TYPE_CODE_0 = sTD_LOAN_STRUC_INT_RATE_TYPE_CODE_0;
	}
	public void setSTD_LOAN_FEE_CODE_0(String sTD_LOAN_FEE_CODE_0) {
		STD_LOAN_FEE_CODE_0 = sTD_LOAN_FEE_CODE_0;
	}
	public void setSTD_LOAN_FEE_EFFDATE_0(String sTD_LOAN_FEE_EFFDATE_0) {
		STD_LOAN_FEE_EFFDATE_0 = sTD_LOAN_FEE_EFFDATE_0;
	}
	public void setSTD_LOAN_FEE_AMOUNT_0(String sTD_LOAN_FEE_AMOUNT_0) {
		STD_LOAN_FEE_AMOUNT_0 = sTD_LOAN_FEE_AMOUNT_0;
	}
	public void setSTD_LOAN_FEE_MTHD_CODE_0(String sTD_LOAN_FEE_MTHD_CODE_0) {
		STD_LOAN_FEE_MTHD_CODE_0 = sTD_LOAN_FEE_MTHD_CODE_0;
	}
	public void setSTD_LOAN_TERM_LOAN_REASON_CODE_0(
			String sTD_LOAN_TERM_LOAN_REASON_CODE_0) {
		STD_LOAN_TERM_LOAN_REASON_CODE_0 = sTD_LOAN_TERM_LOAN_REASON_CODE_0;
	}
	public void setSTD_LOAN_TERM_LOW_THRESH_0(String sTD_LOAN_TERM_LOW_THRESH_0) {
		STD_LOAN_TERM_LOW_THRESH_0 = sTD_LOAN_TERM_LOW_THRESH_0;
	}
	public void setSTD_LOAN_TERM_HIGH_THRESH_0(String sTD_LOAN_TERM_HIGH_THRESH_0) {
		STD_LOAN_TERM_HIGH_THRESH_0 = sTD_LOAN_TERM_HIGH_THRESH_0;
	}
	public void setSTD_LOAN_TERM_LOAN_TERM_QUAL_0(
			String sTD_LOAN_TERM_LOAN_TERM_QUAL_0) {
		STD_LOAN_TERM_LOAN_TERM_QUAL_0 = sTD_LOAN_TERM_LOAN_TERM_QUAL_0;
	}
	public void setSTD_INT_RATE_ADJ_START_DATE_0(
			String sTD_INT_RATE_ADJ_START_DATE_0) {
		STD_INT_RATE_ADJ_START_DATE_0 = sTD_INT_RATE_ADJ_START_DATE_0;
	}
	public void setSTD_INT_RATE_ADJ_VALUE_0(String sTD_INT_RATE_ADJ_VALUE_0) {
		STD_INT_RATE_ADJ_VALUE_0 = sTD_INT_RATE_ADJ_VALUE_0;
	}
	public void setSTD_LOAN_MAX_AMT_LOW_THRESH_0(
			String sTD_LOAN_MAX_AMT_LOW_THRESH_0) {
		STD_LOAN_MAX_AMT_LOW_THRESH_0 = sTD_LOAN_MAX_AMT_LOW_THRESH_0;
	}
	public void setSTD_LOAN_MAX_AMT_HIGH_THRESH_0(
			String sTD_LOAN_MAX_AMT_HIGH_THRESH_0) {
		STD_LOAN_MAX_AMT_HIGH_THRESH_0 = sTD_LOAN_MAX_AMT_HIGH_THRESH_0;
	}
	public void setSTD_LOAN_MAX_AMT_PERCENT_0(String sTD_LOAN_MAX_AMT_PERCENT_0) {
		STD_LOAN_MAX_AMT_PERCENT_0 = sTD_LOAN_MAX_AMT_PERCENT_0;
	}
	public void setSTD_LOAN_MAX_AMT_LOW_THRESH_1(
			String sTD_LOAN_MAX_AMT_LOW_THRESH_1) {
		STD_LOAN_MAX_AMT_LOW_THRESH_1 = sTD_LOAN_MAX_AMT_LOW_THRESH_1;
	}
	public void setSTD_LOAN_MAX_AMT_HIGH_THRESH_1(
			String sTD_LOAN_MAX_AMT_HIGH_THRESH_1) {
		STD_LOAN_MAX_AMT_HIGH_THRESH_1 = sTD_LOAN_MAX_AMT_HIGH_THRESH_1;
	}
	public void setSTD_LOAN_MAX_AMT_AMOUNT_1(String sTD_LOAN_MAX_AMT_AMOUNT_1) {
		STD_LOAN_MAX_AMT_AMOUNT_1 = sTD_LOAN_MAX_AMT_AMOUNT_1;
	}
	public void setSTD_LOAN_STRUC_PREPAY_RESTRC_PERD_0(
			String sTD_LOAN_STRUC_PREPAY_RESTRC_PERD_0) {
		STD_LOAN_STRUC_PREPAY_RESTRC_PERD_0 = sTD_LOAN_STRUC_PREPAY_RESTRC_PERD_0;
	}
	public void setSTD_LOAN_STRUC_PREPAY_RESTRC_QUAL_0(
			String sTD_LOAN_STRUC_PREPAY_RESTRC_QUAL_0) {
		STD_LOAN_STRUC_PREPAY_RESTRC_QUAL_0 = sTD_LOAN_STRUC_PREPAY_RESTRC_QUAL_0;
	}
	public void setSTD_LOAN_STRUC_FULL_PREPAY_ALLOWED_IND_FULL_PREPAY_NO_0(
			String sTD_LOAN_STRUC_FULL_PREPAY_ALLOWED_IND_FULL_PREPAY_NO_0) {
		STD_LOAN_STRUC_FULL_PREPAY_ALLOWED_IND_FULL_PREPAY_NO_0 = sTD_LOAN_STRUC_FULL_PREPAY_ALLOWED_IND_FULL_PREPAY_NO_0;
	}
	public void setSTD_LOAN_STRUC_PAY_AHEAD_ALLOWED_IND_PAY_AHEAD_NO_0(
			String sTD_LOAN_STRUC_PAY_AHEAD_ALLOWED_IND_PAY_AHEAD_NO_0) {
		STD_LOAN_STRUC_PAY_AHEAD_ALLOWED_IND_PAY_AHEAD_NO_0 = sTD_LOAN_STRUC_PAY_AHEAD_ALLOWED_IND_PAY_AHEAD_NO_0;
	}
	public void setSTD_LOAN_STRUC_PRINCIPAL_REDUCTION_ALLOW_IND_PRINCIPAL_REDUCTION_NO_0(
			String sTD_LOAN_STRUC_PRINCIPAL_REDUCTION_ALLOW_IND_PRINCIPAL_REDUCTION_NO_0) {
		STD_LOAN_STRUC_PRINCIPAL_REDUCTION_ALLOW_IND_PRINCIPAL_REDUCTION_NO_0 = sTD_LOAN_STRUC_PRINCIPAL_REDUCTION_ALLOW_IND_PRINCIPAL_REDUCTION_NO_0;
	}
	
	public void setServiceParameters()	
	{
		Random rnd = new Random();
		this.setLOGON_DATABASE(Stock.GetParameterValue("LOGON_DATABASE"));
		this.setLOGON_PASSWORD(Stock.GetParameterValue("LOGON_PASSWORD"));
		this.setLOGON_USERNAME(Stock.GetParameterValue("LOGON_USERNAME"));
		this.setCONTROL_SELECTION_0(Stock.GetParameterValue("CONTROL_SELECTION_0"));
		this.setSTD_INT_RATE_ADJ_START_DATE_0(Stock.GetParameterValue("STD_INT_RATE_ADJ_START_DATE_0"));
		this.setSTD_INT_RATE_ADJ_VALUE_0(Stock.GetParameterValue("STD_INT_RATE_ADJ_VALUE_0"));
		this.setSTD_LOAN_FEE_AMOUNT_0(Stock.GetParameterValue("STD_LOAN_FEE_AMOUNT_0"));
		this.setSTD_LOAN_FEE_CODE_0(Stock.GetParameterValue("STD_LOAN_FEE_CODE_0"));
		this.setSTD_LOAN_FEE_EFFDATE_0(Stock.GetParameterValue("STD_LOAN_FEE_EFFDATE_0"));
		this.setSTD_LOAN_FEE_MTHD_CODE_0(Stock.GetParameterValue("STD_LOAN_FEE_MTHD_CODE_0"));
		this.setSTD_LOAN_MAX_AMT_AMOUNT_1(Stock.GetParameterValue("STD_LOAN_MAX_AMT_AMOUNT_1"));
		this.setSTD_LOAN_MAX_AMT_HIGH_THRESH_0(Stock.GetParameterValue("STD_LOAN_MAX_AMT_HIGH_THRESH_0"));
		this.setSTD_LOAN_MAX_AMT_HIGH_THRESH_1(Stock.GetParameterValue("STD_LOAN_MAX_AMT_HIGH_THRESH_1"));
		this.setSTD_LOAN_MAX_AMT_LOW_THRESH_0(Stock.GetParameterValue("STD_LOAN_MAX_AMT_LOW_THRESH_0"));
		this.setSTD_LOAN_MAX_AMT_LOW_THRESH_1(Stock.GetParameterValue("STD_LOAN_MAX_AMT_LOW_THRESH_1"));
		this.setSTD_LOAN_MAX_AMT_PERCENT_0(Stock.GetParameterValue("STD_LOAN_MAX_AMT_PERCENT_0"));
		this.setSTD_LOAN_STRUC_CODE_0(Stock.GetParameterValue("STD_LOAN_STRUC_CODE_0")+rnd.nextInt(10000));
		this.setSTD_LOAN_STRUC_COLLATERAL_FACTOR_0(Stock.GetParameterValue("STD_LOAN_STRUC_COLLATERAL_FACTOR_0"));
		this.setSTD_LOAN_STRUC_CONSOLIDATE_IND_CONSOLIDATE_NO_RAD_BUT_0(Stock.GetParameterValue("STD_LOAN_STRUC_CONSOLIDATE_IND_CONSOLIDATE_NO_RAD_BUT_0"));
		this.setSTD_LOAN_STRUC_DEBIT_METHOD_CODE_0(Stock.GetParameterValue("STD_LOAN_STRUC_DEBIT_METHOD_CODE_0"));
		this.setSTD_LOAN_STRUC_DEFAULT_TYPE_CODE_0(Stock.GetParameterValue("STD_LOAN_STRUC_DEFAULT_TYPE_CODE_0"));
		this.setSTD_LOAN_STRUC_EARLY_PAYOFF_GRACE_DAYS_0(Stock.GetParameterValue("STD_LOAN_STRUC_EARLY_PAYOFF_GRACE_DAYS_0"));
		this.setSTD_LOAN_STRUC_EARLY_PAYOFF_INT_DAYS_0(Stock.GetParameterValue("STD_LOAN_STRUC_EARLY_PAYOFF_INT_DAYS_0"));
		this.setSTD_LOAN_STRUC_EFFDATE_0(Stock.GetParameterValue("STD_LOAN_STRUC_EFFDATE_0"));
		this.setSTD_LOAN_STRUC_EFFDATE_MTHD_DAYS_0(Stock.GetParameterValue("STD_LOAN_STRUC_EFFDATE_MTHD_DAYS_0"));
		this.setSTD_LOAN_STRUC_FULL_PREPAY_ALLOWED_IND_FULL_PREPAY_NO_0(Stock.GetParameterValue("STD_LOAN_STRUC_FULL_PREPAY_ALLOWED_IND_FULL_PREPAY_NO_0"));
		this.setSTD_LOAN_STRUC_INT_RATE_TYPE_CODE_0(Stock.GetParameterValue("STD_LOAN_STRUC_INT_RATE_TYPE_CODE_0"));
		this.setSTD_LOAN_STRUC_LOAN_TYPE_CODE_0(Stock.GetParameterValue("STD_LOAN_STRUC_LOAN_TYPE_CODE_0"));
		this.setSTD_LOAN_STRUC_MIN_LOAN_AMT_0(Stock.GetParameterValue("STD_LOAN_STRUC_MIN_LOAN_AMT_0"));
		this.setSTD_LOAN_STRUC_PAY_AHEAD_ALLOWED_IND_PAY_AHEAD_NO_0(Stock.GetParameterValue("STD_LOAN_STRUC_PAY_AHEAD_ALLOWED_IND_PAY_AHEAD_NO_0"));
		this.setSTD_LOAN_STRUC_PAY_AHEAD_MAX_DAYS_0(Stock.GetParameterValue("STD_LOAN_STRUC_PAY_AHEAD_MAX_DAYS_0"));
		this.setSTD_LOAN_STRUC_PAYOFF_TOLERANCE_AMT_0(Stock.GetParameterValue("STD_LOAN_STRUC_PAYOFF_TOLERANCE_AMT_0"));
		this.setSTD_LOAN_STRUC_PREPAY_ALLOWED_CODE_0(Stock.GetParameterValue("STD_LOAN_STRUC_PREPAY_ALLOWED_CODE_0"));
		this.setSTD_LOAN_STRUC_PREPAY_RESTRC_PERD_0(Stock.GetParameterValue("STD_LOAN_STRUC_PREPAY_RESTRC_PERD_0"));
		this.setSTD_LOAN_STRUC_PREPAY_RESTRC_QUAL_0(Stock.GetParameterValue("STD_LOAN_STRUC_PREPAY_RESTRC_QUAL_0"));
		this.setSTD_LOAN_STRUC_PRINCIPAL_REDUCTION_ALLOW_IND_PRINCIPAL_REDUCTION_NO_0(Stock.GetParameterValue("STD_LOAN_STRUC_PRINCIPAL_REDUCTION_ALLOW_IND_PRINCIPAL_REDUCTION_NO_0"));
		this.setSTD_LOAN_STRUC_REPAY_CURE_PERD_DAYS_0(Stock.GetParameterValue("STD_LOAN_STRUC_REPAY_CURE_PERD_DAYS_0"));
		this.setSTD_LOAN_STRUC_REPAY_MTHD_CODE_0(Stock.GetParameterValue("STD_LOAN_STRUC_REPAY_MTHD_CODE_0"));
		this.setSTD_LOAN_STRUC_REPAY_TOLERANCE_AMT_0(Stock.GetParameterValue("STD_LOAN_STRUC_REPAY_TOLERANCE_AMT_0"));
		this.setSTD_LOAN_STRUC_SDIRTY_CODE_0(Stock.GetParameterValue("STD_LOAN_STRUC_SDIRTY_CODE_0"));
		this.setSTD_LOAN_STRUC_STRUC_DESCR_0(Stock.GetParameterValue("STD_LOAN_STRUC_STRUC_DESCR_0"));
		this.setSTD_LOAN_TERM_HIGH_THRESH_0(Stock.GetParameterValue("STD_LOAN_TERM_HIGH_THRESH_0"));
		this.setSTD_LOAN_TERM_LOAN_REASON_CODE_0(Stock.GetParameterValue("STD_LOAN_TERM_LOAN_REASON_CODE_0"));
		this.setSTD_LOAN_TERM_LOAN_TERM_QUAL_0(Stock.GetParameterValue("STD_LOAN_TERM_LOAN_TERM_QUAL_0"));
		this.setSTD_LOAN_TERM_LOW_THRESH_0(Stock.GetParameterValue("STD_LOAN_TERM_LOW_THRESH_0"));
		
		
		queryString = "?LOGON_USERNAME="+LOGON_USERNAME+
					  "&LOGON_PASSWORD="+LOGON_PASSWORD+
					  "&LOGON_DATABASE="+LOGON_DATABASE+
					  "&CONTROL_SELECTION_0="+CONTROL_SELECTION_0+
					  "&STD_LOAN_STRUC_CODE_0="+STD_LOAN_STRUC_CODE_0+
					  "&STD_LOAN_STRUC_STRUC_DESCR_0="+STD_LOAN_STRUC_STRUC_DESCR_0+
					  "&STD_LOAN_STRUC_LOAN_TYPE_CODE_0="+STD_LOAN_STRUC_LOAN_TYPE_CODE_0+
					  "&STD_LOAN_STRUC_EFFDATE_0="+STD_LOAN_STRUC_EFFDATE_0+
					  "&STD_LOAN_STRUC_EFFDATE_MTHD_DAYS_0="+STD_LOAN_STRUC_EFFDATE_MTHD_DAYS_0+
					  "&STD_LOAN_STRUC_COLLATERAL_FACTOR_0="+STD_LOAN_STRUC_COLLATERAL_FACTOR_0+
					  "&STD_LOAN_STRUC_MIN_LOAN_AMT_0="+STD_LOAN_STRUC_MIN_LOAN_AMT_0+
					  "&STD_LOAN_STRUC_DEBIT_METHOD_CODE_0="+STD_LOAN_STRUC_DEBIT_METHOD_CODE_0+
					  "&STD_LOAN_STRUC_CONSOLIDATE_IND_CONSOLIDATE_NO_RAD_BUT_0="+STD_LOAN_STRUC_CONSOLIDATE_IND_CONSOLIDATE_NO_RAD_BUT_0+
					  "&STD_LOAN_STRUC_REPAY_MTHD_CODE_0="+STD_LOAN_STRUC_REPAY_MTHD_CODE_0+
					  "&STD_LOAN_STRUC_REPAY_TOLERANCE_AMT_0="+STD_LOAN_STRUC_REPAY_TOLERANCE_AMT_0+
					  "&STD_LOAN_STRUC_REPAY_CURE_PERD_DAYS_0="+STD_LOAN_STRUC_REPAY_CURE_PERD_DAYS_0+
					  "&STD_LOAN_STRUC_DEFAULT_TYPE_CODE_0="+STD_LOAN_STRUC_DEFAULT_TYPE_CODE_0+
					  "&STD_LOAN_STRUC_PREPAY_ALLOWED_CODE_0="+STD_LOAN_STRUC_PREPAY_ALLOWED_CODE_0+
					  "&STD_LOAN_STRUC_PAYOFF_TOLERANCE_AMT_0="+STD_LOAN_STRUC_PAYOFF_TOLERANCE_AMT_0+
					  "&STD_LOAN_STRUC_PAY_AHEAD_MAX_DAYS_0="+STD_LOAN_STRUC_PAY_AHEAD_MAX_DAYS_0+
					  "&STD_LOAN_STRUC_EARLY_PAYOFF_INT_DAYS_0="+STD_LOAN_STRUC_EARLY_PAYOFF_INT_DAYS_0+
					  "&STD_LOAN_STRUC_EARLY_PAYOFF_GRACE_DAYS_0="+STD_LOAN_STRUC_EARLY_PAYOFF_GRACE_DAYS_0+
					  "&STD_LOAN_STRUC_SDIRTY_CODE_0="+STD_LOAN_STRUC_SDIRTY_CODE_0+
					  "&STD_LOAN_STRUC_INT_RATE_TYPE_CODE_0="+STD_LOAN_STRUC_INT_RATE_TYPE_CODE_0+
					  "&STD_LOAN_FEE_CODE_0="+STD_LOAN_FEE_CODE_0+
					  "&STD_LOAN_FEE_EFFDATE_0="+STD_LOAN_FEE_EFFDATE_0+
					  "&STD_LOAN_FEE_AMOUNT_0="+STD_LOAN_FEE_AMOUNT_0+
					  "&STD_LOAN_FEE_MTHD_CODE_0="+STD_LOAN_FEE_MTHD_CODE_0+
					  "&STD_LOAN_TERM_LOAN_REASON_CODE_0="+STD_LOAN_TERM_LOAN_REASON_CODE_0+
					  "&STD_LOAN_TERM_LOW_THRESH_0="+STD_LOAN_TERM_LOW_THRESH_0+
					  "&STD_LOAN_TERM_HIGH_THRESH_0="+STD_LOAN_TERM_HIGH_THRESH_0+
					  "&STD_LOAN_TERM_LOAN_TERM_QUAL_0="+STD_LOAN_TERM_LOAN_TERM_QUAL_0+
					  "&STD_INT_RATE_ADJ_START_DATE_0="+STD_INT_RATE_ADJ_START_DATE_0+
					  "&STD_INT_RATE_ADJ_VALUE_0="+STD_INT_RATE_ADJ_VALUE_0+
					  "&STD_LOAN_MAX_AMT_LOW_THRESH_0="+STD_LOAN_MAX_AMT_LOW_THRESH_0+
					  "&STD_LOAN_MAX_AMT_HIGH_THRESH_0="+STD_LOAN_MAX_AMT_HIGH_THRESH_0+
					  "&STD_LOAN_MAX_AMT_PERCENT_0="+STD_LOAN_MAX_AMT_PERCENT_0+
					  "&STD_LOAN_MAX_AMT_LOW_THRESH_1="+STD_LOAN_MAX_AMT_LOW_THRESH_1+
					  "&STD_LOAN_MAX_AMT_HIGH_THRESH_1="+STD_LOAN_MAX_AMT_HIGH_THRESH_1+
					  "&STD_LOAN_MAX_AMT_AMOUNT_1="+STD_LOAN_MAX_AMT_AMOUNT_1+
					  "&STD_LOAN_STRUC_PREPAY_RESTRC_PERD_0="+STD_LOAN_STRUC_PREPAY_RESTRC_PERD_0+
					  "&STD_LOAN_STRUC_PREPAY_RESTRC_QUAL_0="+STD_LOAN_STRUC_PREPAY_RESTRC_QUAL_0+
					  "&STD_LOAN_STRUC_FULL_PREPAY_ALLOWED_IND_FULL_PREPAY_NO_0="+STD_LOAN_STRUC_FULL_PREPAY_ALLOWED_IND_FULL_PREPAY_NO_0+
					  "&STD_LOAN_STRUC_PAY_AHEAD_ALLOWED_IND_PAY_AHEAD_NO_0="+STD_LOAN_STRUC_PAY_AHEAD_ALLOWED_IND_PAY_AHEAD_NO_0+
					  "&STD_LOAN_STRUC_PRINCIPAL_REDUCTION_ALLOW_IND_PRINCIPAL_REDUCTION_NO_0="+STD_LOAN_STRUC_PRINCIPAL_REDUCTION_ALLOW_IND_PRINCIPAL_REDUCTION_NO_0+
					  "&numOfRowsInTable=20&json=false&handlePopups=false&useLabelsAsKeys=false";
		
		Reporter.logEvent(Status.INFO, "Prepare test data for LMSS Change service", this.queryString.replaceAll("&", "\n"), false);
		
	}
	
	public void runService() {
		try {
			this.queryString = URLDecoder.decode(this.queryString, "UTF-8");
			serviceURL += this.queryString;
			System.out.println(serviceURL);
			docBuilderFactory = DocumentBuilderFactory.newInstance();
			docBuilderFactory.setIgnoringComments(true);
			docBuilderFactory.setIgnoringElementContentWhitespace(true);
			docBuilderFactory.setNamespaceAware(true);
			docBuilder = docBuilderFactory.newDocumentBuilder();
			doc = docBuilder.parse(serviceURL);
			doc.getDocumentElement().normalize();
			Reporter.logEvent(Status.PASS, "Run LMSS service", "Execution Done!", false);
		} catch (Exception e) {
			e.printStackTrace();
			Globals.exception = e;
			Reporter.logEvent(Status.FAIL, "Run LMSS service", "Running Failed:", false);
		}
	}
	
	public void validateOutput() throws SQLException
	{
		String Error = doc.getElementsByTagName("Error").item(0).getTextContent();

		if (Error.isEmpty()){
			Reporter.logEvent(Status.PASS, "Validate response - Error is empty", "Error tag is empty", false);
			System.out.println(doc.getElementsByTagName("PopupMessages").item(0).getTextContent());
			System.out.println(doc.getElementsByTagName("StatusBarMessages").item(0).getTextContent());
			/*Reporter.logEvent(Status.PASS, "From Response: ", 
					"\nSTD_LOAN_STRUC_DEFAULT_LOAN_PREPAY_MTHD_CODE_0: "+doc.getElementsByTagName("STD_LOAN_STRUC_DEFAULT_LOAN_PREPAY_MTHD_CODE_0").item(0).getTextContent()+
					"\nSTD_LOAN_STRUC_TERMDATE_0: "+doc.getElementsByTagName("STD_LOAN_STRUC_TERMDATE_0").item(0).getTextContent()+
					"\nSTD_LOAN_STRUC_INT_CR_MTHD_CODE_0: "+doc.getElementsByTagName("STD_LOAN_STRUC_INT_CR_MTHD_CODE_0").item(0).getTextContent()+
					"\nSTD_LOAN_STRUC_INT_RATE_CHANGE_MTHD_0: "+doc.getElementsByTagName("STD_LOAN_STRUC_INT_RATE_CHANGE_MTHD_0").item(0).getTextContent()+
					"\nDATE_BLOCK_TODAYS_DATE_0: "+doc.getElementsByTagName("DATE_BLOCK_TODAYS_DATE_0").item(0).getTextContent()
					, false);*/
		
		} else {
			Reporter.logEvent(Status.FAIL, "Validate response - Error is empty", "Error tag is not empty\nActual value:\n" + Error, false);
			System.out.println(Error);
		}
	}
	
	public void validateInDatabase()throws SQLException, ParseException{
		String struc_code = this.STD_LOAN_STRUC_CODE_0;
		
		queryResultSet = DB.executeQuery(General.dbInstance, Stock.getTestQuery("queryForLMSS")[1],struc_code);
		
		if(DB.getRecordSetCount(queryResultSet)>0){
			Reporter.logEvent(Status.PASS, "Validating records inserted into DB", "Records inserted into DB:\nTablename: STD_LOAN_Struc", false);
			while(queryResultSet.next()){
				Reporter.logEvent(Status.INFO, "Values from DB", "CODE: "+queryResultSet.getString("CODE")+
						"\nEFFDATE: "+queryResultSet.getString("EFFDATE")+
						"\nSTRUC_DESCR: "+queryResultSet.getString("STRUC_DESCR"), false);
			}
		}
		else
		{
			Reporter.logEvent(Status.FAIL, "Validating from DATABASE","Record not getting created",false);
		}
		
	} 
	
	public void flushData() throws SQLException{
		queryResultSet = DB.executeQuery(General.dbInstance, Stock.getTestQuery("queryForLMSSReset")[1], this.STD_LOAN_STRUC_CODE_0);
	}
	
}
